document.getElementById("myHead").innerHTML =
	"<title>Dz - Le_Rebeu</title>"
	+"<h2>DZ - Le_Rebeu's Website</h2>"
	+		"<nav>"
	+			"<ul class='listonglet'>"
	+				"<li>"
	+					"<div class='onglet'>"
	+						"<a href='index.html'>Acceuil</a>"
	+					"</div>"
	+				"</li>"
	+				"<li>"
	+					"<div class='onglet'>"
	+						"<a href='note.html'>Moyennes/Notes</a>"
	+					"</div>"
	+				"</li>"
	+				"<li>"
	+					"<div class='onglet'>"
	+						"<a href='media.html'>Media</a>"
	+					"</div>"
	+				"</li>"
	+				"<li>"
	+					"<div class='onglet'>"
	+						"<a href='agendas.html'>Agendas</a>"
	+					"</div>"
	+				"</li>"
	+				"<li>"
	+					"<div class='onglet'>"
	+						"<a href='journal.html'>Journal</a>"
	+					"</div>"
	+				"</li>"
	+			"</ul>"
	+		"</nav>";

document.getElementById("myFooter").innerHTML =
	"<p id='copyright' align='right'>Copyright &copy; " + new Date().getFullYear() + "</p>"
	+ "<p id='credits' align='right'>Site crée par Le_Rebeu</p>";